spring:
  liquibase:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always

logging:
  level:
    root: info