version: '3'
services:
  traefik:
    networks:
      - ink_default
    image: traefik:v2.5
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ink_default"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=naruhodo627@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080" # Traefik dashboard on port 8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"

http:
  middlewares:
    redirectScheme:
      redirectScheme:
        scheme: https
        permanent: true

  routers:
    httpToHttps:
      entryPoints:
        - web
      middlewares:
        - redirectScheme
      rule: "HostRegexp(`{any:.+}`)"
      service: "noop"

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://192.168.0.1"


networks:
  ink_default:
    external: true
