version: '3'
services:
  traefik:
    networks:
      - ink_default
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8082:8080" # Traefik dashboard on port 8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  ink_default:
    external: true
