version: '3'
services:
  traefik:
    networks:
      - ink_default
    image: traefik:v2.5
    command:
      - "--configFile=/etc/traefik/traefik-config.yaml"
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ink_default"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=naruhodo627@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8082:8080" # Traefik dashboard on port 8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./letsencrypt:/letsencrypt"
      - "./traefik-config.yaml:/etc/traefik/traefik-config.yaml"

networks:
  ink_default:
    external: true
