name: Test and Deploy with Noti - Dev

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
  push:
    branches:
      - main
    paths:
      - 'ink-core/**'
      - 'ink-api/**'
      - '.github/workflows/test-and-deploy-api-dev.yaml'
      - 'deployment/docker-compose-api-dev.yml'

env:
  JAR_NAME: ink-api-0.0.1-SNAPSHOT.jar
  DEPLOYMENT_NAME: ink-api-deployment # Add your deployment name here.
  IMAGE: ink

jobs:
  test:
    name: Gradle 테스트
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Gradle 빌드 캐싱
        id: gradle-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: application-dev.yml 디코딩
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'application-dev.yml'
          fileDir: './ink-core/src/main/resources/'
          encodedString: ${{ secrets.APPLICATION_YML_DEV_BASE64 }}
      - name: Gradle 테스트 및 실행파일 생성
        run: ./gradlew :ink-api:build :ink-api:test :ink-api:bootJar -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Seoul --info

      - uses: actions/upload-artifact@v2
        name: 생성한 파일 업로드
        with:
          name: ink-api-artifact
          path: ${{ github.workspace }}/ink-api/build/libs/${{ env.JAR_NAME }}
          retention-days: 1
  deployment-api:
    name: Setup, Build, Publish, and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 업로드한 파일 다운로드
        uses: actions/download-artifact@v2
        with:
          name: ink-api-artifact

      - name: 업로드한 파일 빌드 경로로 위치
        run: |
          mkdir ink-api/build
          mkdir ink-api/build/libs
          mv ${{ env.JAR_NAME }} ink-api/build/libs/

      - name: SHA 업데이트
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - name: 이미지 태그 준비
        id: get-tag
        run: |
          tag=$(echo $GITHUB_SHA | head -c7)
          echo "::set-output name=tag::$tag"

      - name: 도커 캐싱 준비
        uses: docker/setup-buildx-action@v1

      - name: 도커 레이어 캐싱
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: 도커 로그인
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: 컨테이너 이미지 빌드 및 이미지 푸쉬
        uses: docker/build-push-action@v2
        with:
          context: ./ink-api/
          push: true
          tags: docker.io/${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE }}:${{ steps.get-tag.outputs.tag }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: 캐시 삭제
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: 환경변수 치환 후 최종 배포 파일 생성
        uses: danielr1996/envsubst-action@1.0.0
        env:
          VERSION: ${{ steps.get-tag.outputs.tag }}
          IMAGE: ink
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          CLOUD_AWS_CREDENTIALS_ACCESS_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}
          CLOUD_AWS_CREDENTIALS_SECRET_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}
        with:
          input: deployment/docker-compose-api-dev.yml
          output: docker-compose.yml

      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to Server
        env:
          DOCKER_COMPOSE_FILE: docker-compose.yml
        run: |
          # Make a directory
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ vars.PATH_TO_REMOTE }}"
          
          # Copy docker-compose.yml file to the remote server
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P ${{ secrets.SSH_PORT }} $DOCKER_COMPOSE_FILE ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ vars.PATH_TO_REMOTE }}/docker-compose.yml

          # SSH to the remote server and deploy the Docker container using Docker Compose
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ vars.PATH_TO_REMOTE }} && docker-compose pull ink_backend_api && docker-compose down && docker-compose up -d"

      - uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}

